# Generated by Django 5.2 on 2025-04-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Aurarette', max_length=100)),
                ('body', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About page',
            },
        ),
    ]
